fix: make `useCdn` use `true` by default
sanity-io/client pull request #191
Opened 2023-04-04 18:46 UTC by stipsan

# Why `true` is better
Seeing unexpected stale content is a far better problem to have than a surprise overage bill 😅 
[This is a follow up to this discussion.](https://sanity-io.slack.com/archives/C043ZRB9E4S/p1680101505217759)

Also worth noting that one of the historical reasons why `useCdn: false` have been the default were the limitation the client had prior to `v3`: https://www.sanity.io/help/js-client-cdn-configuration#:~:text=subscribing%20to%20changes).-,Gotcha,-Prior%20to%20v3.0.0
Now that the client have supported using `token` with `useCdn: true` for quite some time it makes sense to change the default.

# Why make it a `patch` release instead of `major`
For users that have `useCdn: undefined` this is technically a "breaking" change. 
But as we've been nudging people to set it to `true` or `false`, and we've been consistent about this in our starter templates, docs and educational materials: https://github.com/sanity-io/client/blob/9ebbb7c81272c38c502378516f7c6eef17ff4ba7/src/warnings.ts#L10-L13

Doing what's best in the interest of the users here should outweigh the desire to be semver pedantic. If we make a major release my fear is that the ecosystem churn that'll result from it (needing to make new releases of `sanity`, `next-sanity`, starters, plugins) would be a really expensive price to pay and the benefits no longer justifiable 😅

2023-04-04 20:22 UTC, kmelve commented
This is a neat way of preventing some of the unintended cases of hitting the API limits.

The semver but is a bit tricky, but then again, everyone who have been using this with undefined should have seen the warning. It seems unlikely that someone are relying on the undefined behavior for business critical functionality. 

That being said, what's unclear to me is how we can make sure that the developer experience for folks that use the client to fetch content for static rendering isn't getting more confusing, as well as typical onboarding scenarios, and local development feedback loops. 

## New users and onboarding 
How will this affect developers new to the platform who are asked to publish a document and see their change in the frontend? Maybe the cache invalidation is quick enough that it's fine? Either way, we should make sure to make a note of this property in new onboarding materials. 

## Documentation
This release could incentivize writing better docs on how our caching actually works, including invalidation. I see the "why aren't I'm seeing my published content" quite often. 

It would also be very helpful if we provided guidance on how to set this property so it works with typical static rendering where builds or frontend revalidation is triggered by a webhook. This also affect content creators who are confused by not seeing their published content. I get that it's slightly outside of this change specifically, but it does bring it into focus.

2023-04-05 16:11 UTC, stipsan commented
To solve the general problem of stale content we could, when publishing a document, show an intermediary "yellow" state: Draft -> Pending/Propagating/Publishing -> Published. 
This state can be disabled in the studio config, it's enabled by default. A mouseover tells you if it's fully available in the API CDN yet or how long until it is (we have metrics on the timing of this).

For the static site building I think it needs better docs indeed that is tailored specifically for that. There's a lot of moving parts, ISR or no, webhooks or no, etc.

2023-04-05 16:35 UTC, runeb commented on README.md
> +Initializes a new Sanity Client. Required options are `projectId`, `dataset`, and `apiVersion`. [We encourage setting `useCdn` to either `true` or `false`.](https://www.sanity.io/help/js-client-cdn-c
@stipsan Suggest changing
> If you're not sure which option to use then stick to `true` and revisit later should stale data prove to cause problems

to

> If you're not sure which option to choose we recommend starting with `true` and revise later if you find that you require uncached content

2023-04-05 16:38 UTC, runeb commented on src/warnings.ts
> +  `You're using the Sanity API CDN. Its edge caching makes it faster and cheaper than the live API. `,
Suggest changing this wording to something like

> You're using the Sanity API CDN which has the fastest and most scalable content delivery. You can opt out if you require uncached content.

2023-04-11 15:59 UTC, runeb requested changes, later dismissed

2023-04-11 15:59 UTC, runeb commented on README.md
> +Initializes a new Sanity Client. Required options are `projectId`, `dataset`, and `apiVersion`. [We encourage setting `useCdn` to either `true` or `false`.](https://www.sanity.io/help/js-client-cdn-c
```suggestion
Initializes a new Sanity Client. Required options are `projectId`, `dataset`, and `apiVersion`. [We encourage setting `useCdn` to either `true` or `false`.](https://www.sanity.io/help/js-client-cdn-configuration) The default is `true`. If you're not sure which option to choose we recommend starting with `true` and revise later if you find that you require uncached content. [Our awesome Slack community can help guide you on how to avoid stale data tailored to your tech stack and architecture.](https://slack.sanity.io/)
```

2023-04-11 15:59 UTC, runeb commented on src/warnings.ts
>    'the client.',
```suggestion
  `Since you haven't set a value for /`useCdn/`, we will deliver content using our`,
  `global, edge-cached API-CDN. If you wish to have content delivered faster, set`,
  `/`useCdn: false`/ to use the Live API. Note: You may incur higher costs using the live API.`,
```

2023-04-11 15:59 UTC, runeb commented on test/warnings.test.ts
> +      "You're using the Sanity API CDN. Its edge caching makes it faster and cheaper than the live API.  For more info, see https://www.sanity.io/help/js-client-cdn-configuration  To hide this warnin
```suggestion
      "Since you have not set a value for useCDN, we will deliver content using our global, edge-cached API-CDN. If you wish to have content delivered faster, set useCDN: false to use the Live API. Note: You may incur higher costs using the live API."
```

2023-04-11 16:01 UTC, runeb commented
Added suggested changes from @tarungangwani

2023-04-11 21:39 UTC, rexxars approved these changes
While the change in and of itself looks fine, I don't agree that this shouldn't be considered a breaking change. People may have just ignored the warnings on app startup, for instance. I'd vote to bump the major version.

2023-04-27 21:23 UTC, merged